CREATE TABLE TB_CUSTOMER (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    cpf VARCHAR(14) UNIQUE NOT NULL
);

CREATE TABLE TB_PRODUCT (
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	price_per_kg NUMERIC(5, 2) NOT NULL
);

CREATE TABLE TB_SALE (
    id SERIAL PRIMARY KEY,
    sale_date DATE NOT NULL,
    total_value NUMERIC(6, 2) NOT NULL,
    payment_status BOOLEAN NOT NULL,
    customer_id INT NOT NULL REFERENCES TB_CUSTOMER (id)
);

CREATE TABLE TB_PURCHASE (
    id serial PRIMARY KEY,
    weight NUMERIC(8, 3) NOT NULL,
    product_id INT NOT NULL REFERENCES TB_PRODUCT (id),
    sale_id INT NOT NULL REFERENCES TB_SALE (id)
);
