DELETE FROM TB_PURCHASE;
DELETE FROM TB_SALE;
DELETE FROM TB_CUSTOMER;
DELETE FROM TB_PRODUCT;

ALTER TABLE TB_SALE DROP COLUMN customer_id;
ALTER TABLE TB_PURCHASE DROP COLUMN sale_id;

ALTER TABLE TB_PURCHASE ADD COLUMN sale_id INT NOT NULL REFERENCES TB_SALE (id) ON DELETE CASCADE;
ALTER TABLE TB_SALE ADD COLUMN customer_id INT NOT NULL REFERENCES TB_CUSTOMER (id) ON DELETE CASCADE;
